baseURL = "http://example.org/"
languageCode = "en-us"
title = "Fort Qu'appelle Duplicate Bridge"
theme = "ananke"
uglyurls = true


[menu]

  [[menu.main]]
    identifier = "results"
    name = "Results"
    pre = "<i class='fa fa-heart'></i>"
    url = "/results"
    weight = -110

  [[menu.main]]
    name = "One Results"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/results/160701a.htm"
    weight = -100
